import { hasLocale, type Locale } from "@/lib/i18n";
import { notFound } from "next/navigation";
import type { Metadata } from "next";

const content = {
  en: {
    title: "Terms of Service",
    lastUpdated: "Last updated: March 31, 2026",
    sections: [
      {
        heading: "1. Acceptance of Terms",
        body: "By accessing or using EasySite (\"Service\"), operated by JY Tech LLC (\"we\", \"us\", \"our\"), you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use the Service.",
      },
      {
        heading: "2. Description of Service",
        body: "EasySite is an AI-powered website builder that allows users to create, publish, and manage static websites. The Service includes AI-generated content, website hosting, Cloudflare Pages integration, and site export features.",
      },
      {
        heading: "3. User Accounts",
        body: "You may use certain features without an account. To access the full Service, you must create an account via Auth0 authentication. You are responsible for maintaining the security of your account credentials and for all activities that occur under your account.",
      },
      {
        heading: "4. Acceptable Use",
        body: "You agree not to use the Service to: (a) create websites that contain illegal, harmful, or offensive content; (b) infringe on any third party's intellectual property rights; (c) distribute malware or phishing content; (d) attempt to gain unauthorized access to the Service or its systems; (e) use automated means to abuse the Service beyond normal usage.",
      },
      {
        heading: "5. Content Ownership",
        body: "You retain ownership of the content you create using the Service. By publishing content through the Service, you grant us a non-exclusive, worldwide license to host and display your content for the purpose of operating the Service. You may export or delete your content at any time.",
      },
      {
        heading: "6. AI-Generated Content",
        body: "Content generated by the AI is provided \"as is\". While we strive for quality, we do not guarantee that AI-generated content will be error-free, accurate, or suitable for any particular purpose. You are responsible for reviewing and editing all AI-generated content before publishing.",
      },
      {
        heading: "7. Third-Party Integrations",
        body: "The Service integrates with third-party services including Cloudflare, Auth0, and Stripe. Your use of these integrations is subject to the respective third-party terms of service. We are not responsible for the availability or performance of third-party services. When using BYOK (Bring Your Own Key) features, you are responsible for managing your own API keys and credentials.",
      },
      {
        heading: "8. Payment and Subscriptions",
        body: "Paid plans are billed monthly through Stripe. You may cancel your subscription at any time. Refunds are handled on a case-by-case basis. If you downgrade your plan, you may lose access to features available only on higher tiers.",
      },
      {
        heading: "9. Service Availability",
        body: "We strive to maintain high availability but do not guarantee uninterrupted access to the Service. We reserve the right to modify, suspend, or discontinue any part of the Service with reasonable notice.",
      },
      {
        heading: "10. Limitation of Liability",
        body: "To the maximum extent permitted by law, JY Tech LLC shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Service. Our total liability shall not exceed the amount you paid us in the 12 months preceding the claim.",
      },
      {
        heading: "11. Termination",
        body: "We may terminate or suspend your account if you violate these terms. Upon termination, your right to use the Service ceases immediately. You may export your content before termination. We may retain certain data as required by law.",
      },
      {
        heading: "12. Changes to Terms",
        body: "We may update these terms from time to time. We will notify you of material changes via email or through the Service. Continued use of the Service after changes constitutes acceptance of the updated terms.",
      },
      {
        heading: "13. Governing Law",
        body: "These terms are governed by the laws of the State of California, United States, without regard to conflict of law principles.",
      },
      {
        heading: "14. Contact",
        body: "For questions about these terms, contact us at support@jytech.us.",
      },
    ],
  },
  zh: {
    title: "服务条款",
    lastUpdated: "最后更新：2026 年 3 月 31 日",
    sections: [
      {
        heading: "1. 条款接受",
        body: "访问或使用由 JY Tech LLC（\"我们\"）运营的 EasySite（\"服务\"），即表示你同意受本服务条款的约束。如果你不同意这些条款，请不要使用本服务。",
      },
      {
        heading: "2. 服务描述",
        body: "EasySite 是一个 AI 驱动的建站工具，允许用户创建、发布和管理静态网站。服务包括 AI 生成内容、网站托管、Cloudflare Pages 集成和网站导出功能。",
      },
      {
        heading: "3. 用户账户",
        body: "你可以在不注册账户的情况下使用部分功能。要使用完整服务，你需要通过 Auth0 认证创建账户。你有责任维护账户凭证的安全，并对账户下的所有活动负责。",
      },
      {
        heading: "4. 可接受的使用",
        body: "你同意不将服务用于：(a) 创建包含违法、有害或冒犯性内容的网站；(b) 侵犯任何第三方知识产权；(c) 传播恶意软件或钓鱼内容；(d) 试图未经授权访问服务或其系统；(e) 使用自动化手段滥用超出正常使用的服务。",
      },
      {
        heading: "5. 内容所有权",
        body: "你保留使用服务创建的内容的所有权。通过服务发布内容，即授予我们非独占的、全球性的许可，用于托管和展示你的内容以运营服务。你可以随时导出或删除你的内容。",
      },
      {
        heading: "6. AI 生成内容",
        body: "AI 生成的内容按\"原样\"提供。尽管我们追求质量，但不保证 AI 生成的内容无错误、准确或适合任何特定用途。你有责任在发布前审核和编辑所有 AI 生成的内容。",
      },
      {
        heading: "7. 第三方集成",
        body: "服务集成了包括 Cloudflare、Auth0 和 Stripe 在内的第三方服务。你使用这些集成须遵守相应的第三方服务条款。我们不对第三方服务的可用性或性能负责。使用 BYOK（自带密钥）功能时，你有责任管理自己的 API 密钥和凭证。",
      },
      {
        heading: "8. 付款和订阅",
        body: "付费计划通过 Stripe 按月计费。你可以随时取消订阅。退款将根据具体情况处理。如果你降级计划，可能会失去仅在更高层级可用的功能。",
      },
      {
        heading: "9. 服务可用性",
        body: "我们努力保持高可用性，但不保证对服务的不间断访问。我们保留在合理通知后修改、暂停或终止服务任何部分的权利。",
      },
      {
        heading: "10. 责任限制",
        body: "在法律允许的最大范围内，JY Tech LLC 不对因使用服务而产生的任何间接、附带、特殊、后果性或惩罚性损害承担责任。我们的总责任不超过你在索赔前 12 个月内向我们支付的金额。",
      },
      {
        heading: "11. 终止",
        body: "如果你违反这些条款，我们可能会终止或暂停你的账户。终止后，你使用服务的权利立即停止。你可以在终止前导出你的内容。我们可能会根据法律要求保留某些数据。",
      },
      {
        heading: "12. 条款变更",
        body: "我们可能会不时更新这些条款。重大变更将通过电子邮件或服务通知你。在变更后继续使用服务即表示接受更新后的条款。",
      },
      {
        heading: "13. 适用法律",
        body: "本条款受美国加利福尼亚州法律管辖，不考虑法律冲突原则。",
      },
      {
        heading: "14. 联系方式",
        body: "如有关于本条款的问题，请联系 support@jytech.us。",
      },
    ],
  },
  es: {
    title: "Términos de Servicio",
    lastUpdated: "Última actualización: 31 de marzo de 2026",
    sections: [
      {
        heading: "1. Aceptación de los Términos",
        body: "Al acceder o utilizar EasySite (\"Servicio\"), operado por JY Tech LLC (\"nosotros\", \"nuestro\"), usted acepta estar sujeto a estos Términos de Servicio. Si no está de acuerdo con estos términos, no utilice el Servicio.",
      },
      {
        heading: "2. Descripción del Servicio",
        body: "EasySite es un creador de sitios web impulsado por IA que permite a los usuarios crear, publicar y administrar sitios web estáticos. El Servicio incluye contenido generado por IA, alojamiento de sitios web, integración con Cloudflare Pages y funciones de exportación de sitios.",
      },
      {
        heading: "3. Cuentas de Usuario",
        body: "Puede utilizar ciertas funciones sin una cuenta. Para acceder al Servicio completo, debe crear una cuenta mediante la autenticación de Auth0. Usted es responsable de mantener la seguridad de las credenciales de su cuenta y de todas las actividades que ocurran bajo su cuenta.",
      },
      {
        heading: "4. Uso Aceptable",
        body: "Usted acepta no utilizar el Servicio para: (a) crear sitios web que contengan contenido ilegal, dañino u ofensivo; (b) infringir los derechos de propiedad intelectual de terceros; (c) distribuir malware o contenido de phishing; (d) intentar obtener acceso no autorizado al Servicio o sus sistemas; (e) utilizar medios automatizados para abusar del Servicio más allá del uso normal.",
      },
      {
        heading: "5. Propiedad del Contenido",
        body: "Usted conserva la propiedad del contenido que crea utilizando el Servicio. Al publicar contenido a través del Servicio, nos otorga una licencia no exclusiva y mundial para alojar y mostrar su contenido con el fin de operar el Servicio. Puede exportar o eliminar su contenido en cualquier momento.",
      },
      {
        heading: "6. Contenido Generado por IA",
        body: "El contenido generado por la IA se proporciona \"tal cual\". Aunque nos esforzamos por la calidad, no garantizamos que el contenido generado por IA esté libre de errores, sea preciso o adecuado para cualquier propósito particular. Usted es responsable de revisar y editar todo el contenido generado por IA antes de publicarlo.",
      },
      {
        heading: "7. Integraciones de Terceros",
        body: "El Servicio se integra con servicios de terceros, incluidos Cloudflare, Auth0 y Stripe. Su uso de estas integraciones está sujeto a los respectivos términos de servicio de terceros. No somos responsables de la disponibilidad o el rendimiento de los servicios de terceros. Al utilizar las funciones BYOK (Traiga Su Propia Clave), usted es responsable de administrar sus propias claves API y credenciales.",
      },
      {
        heading: "8. Pago y Suscripciones",
        body: "Los planes de pago se facturan mensualmente a través de Stripe. Puede cancelar su suscripción en cualquier momento. Los reembolsos se manejan caso por caso. Si reduce su plan, puede perder acceso a funciones disponibles solo en niveles superiores.",
      },
      {
        heading: "9. Disponibilidad del Servicio",
        body: "Nos esforzamos por mantener una alta disponibilidad, pero no garantizamos el acceso ininterrumpido al Servicio. Nos reservamos el derecho de modificar, suspender o descontinuar cualquier parte del Servicio con un aviso razonable.",
      },
      {
        heading: "10. Limitación de Responsabilidad",
        body: "En la máxima medida permitida por la ley, JY Tech LLC no será responsable de ningún daño indirecto, incidental, especial, consecuente o punitivo derivado de su uso del Servicio. Nuestra responsabilidad total no excederá la cantidad que nos haya pagado en los 12 meses anteriores a la reclamación.",
      },
      {
        heading: "11. Terminación",
        body: "Podemos terminar o suspender su cuenta si viola estos términos. Tras la terminación, su derecho a usar el Servicio cesa inmediatamente. Puede exportar su contenido antes de la terminación. Podemos retener ciertos datos según lo requiera la ley.",
      },
      {
        heading: "12. Cambios en los Términos",
        body: "Podemos actualizar estos términos de vez en cuando. Le notificaremos sobre cambios importantes por correo electrónico o a través del Servicio. El uso continuado del Servicio después de los cambios constituye la aceptación de los términos actualizados.",
      },
      {
        heading: "13. Ley Aplicable",
        body: "Estos términos se rigen por las leyes del Estado de California, Estados Unidos, sin tener en cuenta los principios de conflicto de leyes.",
      },
      {
        heading: "14. Contacto",
        body: "Para preguntas sobre estos términos, contáctenos en support@jytech.us.",
      },
    ],
  },
  ko: {
    title: "서비스 약관",
    lastUpdated: "최종 업데이트: 2026년 3월 31일",
    sections: [
      {
        heading: "1. 약관 동의",
        body: "JY Tech LLC(\"당사\")가 운영하는 EasySite(\"서비스\")에 접근하거나 사용함으로써 귀하는 본 서비스 약관에 구속되는 것에 동의합니다. 본 약관에 동의하지 않는 경우 서비스를 사용하지 마십시오.",
      },
      {
        heading: "2. 서비스 설명",
        body: "EasySite는 사용자가 정적 웹사이트를 생성, 게시 및 관리할 수 있는 AI 기반 웹사이트 빌더입니다. 서비스에는 AI 생성 콘텐츠, 웹사이트 호스팅, Cloudflare Pages 통합 및 사이트 내보내기 기능이 포함됩니다.",
      },
      {
        heading: "3. 사용자 계정",
        body: "계정 없이도 일부 기능을 사용할 수 있습니다. 전체 서비스에 접근하려면 Auth0 인증을 통해 계정을 생성해야 합니다. 귀하는 계정 자격 증명의 보안을 유지하고 계정에서 발생하는 모든 활동에 대해 책임을 집니다.",
      },
      {
        heading: "4. 허용되는 사용",
        body: "귀하는 서비스를 다음 목적으로 사용하지 않을 것에 동의합니다: (a) 불법적이거나 유해하거나 불쾌한 콘텐츠가 포함된 웹사이트 생성; (b) 제3자의 지적 재산권 침해; (c) 악성 소프트웨어 또는 피싱 콘텐츠 배포; (d) 서비스 또는 시스템에 대한 무단 접근 시도; (e) 정상적인 사용을 초과하여 자동화된 수단으로 서비스를 남용.",
      },
      {
        heading: "5. 콘텐츠 소유권",
        body: "귀하는 서비스를 사용하여 생성한 콘텐츠의 소유권을 보유합니다. 서비스를 통해 콘텐츠를 게시함으로써 귀하는 서비스 운영을 위해 콘텐츠를 호스팅하고 표시할 수 있는 비독점적이고 전 세계적인 라이선스를 당사에 부여합니다. 언제든지 콘텐츠를 내보내거나 삭제할 수 있습니다.",
      },
      {
        heading: "6. AI 생성 콘텐츠",
        body: "AI가 생성한 콘텐츠는 \"있는 그대로\" 제공됩니다. 품질을 위해 노력하지만 AI 생성 콘텐츠가 오류가 없거나 정확하거나 특정 목적에 적합하다고 보장하지 않습니다. 게시 전에 모든 AI 생성 콘텐츠를 검토하고 편집할 책임은 귀하에게 있습니다.",
      },
      {
        heading: "7. 제3자 통합",
        body: "서비스는 Cloudflare, Auth0, Stripe를 포함한 제3자 서비스와 통합됩니다. 이러한 통합의 사용은 해당 제3자 서비스 약관의 적용을 받습니다. 당사는 제3자 서비스의 가용성이나 성능에 대해 책임을 지지 않습니다. BYOK(자체 키 사용) 기능을 사용할 때 귀하는 자신의 API 키와 자격 증명을 관리할 책임이 있습니다.",
      },
      {
        heading: "8. 결제 및 구독",
        body: "유료 플랜은 Stripe를 통해 월별로 청구됩니다. 언제든지 구독을 취소할 수 있습니다. 환불은 개별 사례에 따라 처리됩니다. 플랜을 다운그레이드하면 상위 등급에서만 사용 가능한 기능에 대한 접근을 잃을 수 있습니다.",
      },
      {
        heading: "9. 서비스 가용성",
        body: "당사는 높은 가용성을 유지하기 위해 노력하지만 서비스에 대한 중단 없는 접근을 보장하지 않습니다. 당사는 합리적인 통지 후 서비스의 일부를 수정, 일시 중단 또는 중단할 권리를 보유합니다.",
      },
      {
        heading: "10. 책임 제한",
        body: "법이 허용하는 최대 범위 내에서 JY Tech LLC는 서비스 사용으로 인해 발생하는 간접적, 부수적, 특별, 결과적 또는 징벌적 손해에 대해 책임을 지지 않습니다. 당사의 총 책임은 청구 이전 12개월 동안 귀하가 당사에 지불한 금액을 초과하지 않습니다.",
      },
      {
        heading: "11. 해지",
        body: "귀하가 본 약관을 위반하는 경우 당사는 귀하의 계정을 해지하거나 정지할 수 있습니다. 해지 시 서비스를 사용할 권리는 즉시 종료됩니다. 해지 전에 콘텐츠를 내보낼 수 있습니다. 당사는 법률에 따라 특정 데이터를 보유할 수 있습니다.",
      },
      {
        heading: "12. 약관 변경",
        body: "당사는 수시로 본 약관을 업데이트할 수 있습니다. 중요한 변경 사항은 이메일 또는 서비스를 통해 통지합니다. 변경 후 서비스를 계속 사용하면 업데이트된 약관에 동의하는 것으로 간주됩니다.",
      },
      {
        heading: "13. 준거법",
        body: "본 약관은 법률 충돌 원칙에 관계없이 미국 캘리포니아주 법률의 적용을 받습니다.",
      },
      {
        heading: "14. 연락처",
        body: "본 약관에 관한 질문은 support@jytech.us로 문의해 주십시오.",
      },
    ],
  },
};

export async function generateMetadata({
  params,
}: {
  params: Promise<{ locale: string }>;
}): Promise<Metadata> {
  const { locale } = await params;
  if (!hasLocale(locale)) return {};
  const loc = locale as Locale;
  return {
    title: content[loc].title,
  };
}

export default async function TermsPage({
  params,
}: {
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  if (!hasLocale(locale)) notFound();
  const loc = locale as Locale;
  const t = content[loc];

  return (
    <div className="mx-auto max-w-3xl px-4 py-16 sm:py-24">
      <h1 className="text-3xl sm:text-4xl font-bold mb-2">{t.title}</h1>
      <p className="text-sm text-muted mb-10">{t.lastUpdated}</p>
      <div className="space-y-8">
        {t.sections.map((s) => (
          <section key={s.heading}>
            <h2 className="text-lg font-semibold mb-2">{s.heading}</h2>
            <p className="text-muted leading-relaxed">{s.body}</p>
          </section>
        ))}
      </div>
    </div>
  );
}
