import { hasLocale, type Locale } from "@/lib/i18n";
import { notFound } from "next/navigation";
import type { Metadata } from "next";

const content = {
  en: {
    title: "Terms of Service",
    lastUpdated: "Last updated: March 31, 2026",
    sections: [
      {
        heading: "1. Acceptance of Terms",
        body: "By accessing or using EasySite (\"Service\"), operated by JY Tech LLC (\"we\", \"us\", \"our\"), you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use the Service.",
      },
      {
        heading: "2. Description of Service",
        body: "EasySite is an AI-powered website builder that allows users to create, publish, and manage static websites. The Service includes AI-generated content, website hosting, Cloudflare Pages integration, and site export features.",
      },
      {
        heading: "3. User Accounts",
        body: "You may use certain features without an account. To access the full Service, you must create an account via Auth0 authentication. You are responsible for maintaining the security of your account credentials and for all activities that occur under your account.",
      },
      {
        heading: "4. Acceptable Use",
        body: "You agree not to use the Service to: (a) create websites that contain illegal, harmful, or offensive content; (b) infringe on any third party's intellectual property rights; (c) distribute malware or phishing content; (d) attempt to gain unauthorized access to the Service or its systems; (e) use automated means to abuse the Service beyond normal usage.",
      },
      {
        heading: "5. Content Ownership",
        body: "You retain ownership of the content you create using the Service. By publishing content through the Service, you grant us a non-exclusive, worldwide license to host and display your content for the purpose of operating the Service. You may export or delete your content at any time.",
      },
      {
        heading: "6. AI-Generated Content",
        body: "Content generated by the AI is provided \"as is\". While we strive for quality, we do not guarantee that AI-generated content will be error-free, accurate, or suitable for any particular purpose. You are responsible for reviewing and editing all AI-generated content before publishing.",
      },
      {
        heading: "7. Third-Party Integrations",
        body: "The Service integrates with third-party services including Cloudflare, Auth0, and Stripe. Your use of these integrations is subject to the respective third-party terms of service. We are not responsible for the availability or performance of third-party services. When using BYOK (Bring Your Own Key) features, you are responsible for managing your own API keys and credentials.",
      },
      {
        heading: "8. Payment and Subscriptions",
        body: "Paid plans are billed monthly through Stripe. You may cancel your subscription at any time. Refunds are handled on a case-by-case basis. If you downgrade your plan, you may lose access to features available only on higher tiers.",
      },
      {
        heading: "9. Service Availability",
        body: "We strive to maintain high availability but do not guarantee uninterrupted access to the Service. We reserve the right to modify, suspend, or discontinue any part of the Service with reasonable notice.",
      },
      {
        heading: "10. Limitation of Liability",
        body: "To the maximum extent permitted by law, JY Tech LLC shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Service. Our total liability shall not exceed the amount you paid us in the 12 months preceding the claim.",
      },
      {
        heading: "11. Termination",
        body: "We may terminate or suspend your account if you violate these terms. Upon termination, your right to use the Service ceases immediately. You may export your content before termination. We may retain certain data as required by law.",
      },
      {
        heading: "12. Changes to Terms",
        body: "We may update these terms from time to time. We will notify you of material changes via email or through the Service. Continued use of the Service after changes constitutes acceptance of the updated terms.",
      },
      {
        heading: "13. Governing Law",
        body: "These terms are governed by the laws of the State of California, United States, without regard to conflict of law principles.",
      },
      {
        heading: "14. Contact",
        body: "For questions about these terms, contact us at support@jytech.us.",
      },
    ],
  },
  zh: {
    title: "服务条款",
    lastUpdated: "最后更新：2026 年 3 月 31 日",
    sections: [
      {
        heading: "1. 条款接受",
        body: "访问或使用由 JY Tech LLC（\"我们\"）运营的 EasySite（\"服务\"），即表示你同意受本服务条款的约束。如果你不同意这些条款，请不要使用本服务。",
      },
      {
        heading: "2. 服务描述",
        body: "EasySite 是一个 AI 驱动的建站工具，允许用户创建、发布和管理静态网站。服务包括 AI 生成内容、网站托管、Cloudflare Pages 集成和网站导出功能。",
      },
      {
        heading: "3. 用户账户",
        body: "你可以在不注册账户的情况下使用部分功能。要使用完整服务，你需要通过 Auth0 认证创建账户。你有责任维护账户凭证的安全，并对账户下的所有活动负责。",
      },
      {
        heading: "4. 可接受的使用",
        body: "你同意不将服务用于：(a) 创建包含违法、有害或冒犯性内容的网站；(b) 侵犯任何第三方知识产权；(c) 传播恶意软件或钓鱼内容；(d) 试图未经授权访问服务或其系统；(e) 使用自动化手段滥用超出正常使用的服务。",
      },
      {
        heading: "5. 内容所有权",
        body: "你保留使用服务创建的内容的所有权。通过服务发布内容，即授予我们非独占的、全球性的许可，用于托管和展示你的内容以运营服务。你可以随时导出或删除你的内容。",
      },
      {
        heading: "6. AI 生成内容",
        body: "AI 生成的内容按\"原样\"提供。尽管我们追求质量，但不保证 AI 生成的内容无错误、准确或适合任何特定用途。你有责任在发布前审核和编辑所有 AI 生成的内容。",
      },
      {
        heading: "7. 第三方集成",
        body: "服务集成了包括 Cloudflare、Auth0 和 Stripe 在内的第三方服务。你使用这些集成须遵守相应的第三方服务条款。我们不对第三方服务的可用性或性能负责。使用 BYOK（自带密钥）功能时，你有责任管理自己的 API 密钥和凭证。",
      },
      {
        heading: "8. 付款和订阅",
        body: "付费计划通过 Stripe 按月计费。你可以随时取消订阅。退款将根据具体情况处理。如果你降级计划，可能会失去仅在更高层级可用的功能。",
      },
      {
        heading: "9. 服务可用性",
        body: "我们努力保持高可用性，但不保证对服务的不间断访问。我们保留在合理通知后修改、暂停或终止服务任何部分的权利。",
      },
      {
        heading: "10. 责任限制",
        body: "在法律允许的最大范围内，JY Tech LLC 不对因使用服务而产生的任何间接、附带、特殊、后果性或惩罚性损害承担责任。我们的总责任不超过你在索赔前 12 个月内向我们支付的金额。",
      },
      {
        heading: "11. 终止",
        body: "如果你违反这些条款，我们可能会终止或暂停你的账户。终止后，你使用服务的权利立即停止。你可以在终止前导出你的内容。我们可能会根据法律要求保留某些数据。",
      },
      {
        heading: "12. 条款变更",
        body: "我们可能会不时更新这些条款。重大变更将通过电子邮件或服务通知你。在变更后继续使用服务即表示接受更新后的条款。",
      },
      {
        heading: "13. 适用法律",
        body: "本条款受美国加利福尼亚州法律管辖，不考虑法律冲突原则。",
      },
      {
        heading: "14. 联系方式",
        body: "如有关于本条款的问题，请联系 support@jytech.us。",
      },
    ],
  },
};

export async function generateMetadata({
  params,
}: {
  params: Promise<{ locale: string }>;
}): Promise<Metadata> {
  const { locale } = await params;
  if (!hasLocale(locale)) return {};
  const loc = locale as Locale;
  return {
    title: content[loc].title,
  };
}

export default async function TermsPage({
  params,
}: {
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  if (!hasLocale(locale)) notFound();
  const loc = locale as Locale;
  const t = content[loc];

  return (
    <div className="mx-auto max-w-3xl px-4 py-16 sm:py-24">
      <h1 className="text-3xl sm:text-4xl font-bold mb-2">{t.title}</h1>
      <p className="text-sm text-muted mb-10">{t.lastUpdated}</p>
      <div className="space-y-8">
        {t.sections.map((s) => (
          <section key={s.heading}>
            <h2 className="text-lg font-semibold mb-2">{s.heading}</h2>
            <p className="text-muted leading-relaxed">{s.body}</p>
          </section>
        ))}
      </div>
    </div>
  );
}
